Feature: Creating of admin functionality

  Background: Login
    Given Enter email super@gmail.com
    And Enter password Sa1234567+
    And Click on 'login' button
    Then Click on 'create' button and open popup

  Scenario: Check functionality of 'Create' button in super admin dashboard - TC 1.6.1
    Then Check all fields are present in create popup

  Scenario: Check functionality of 'X' button - TC 1.6.2
    And Fill name Vaxinak
    When Click on 'X' button
    And Popup is closed
    Then Check all input fields are empty in create popup

  Scenario: Check functionality of 'Generate password' button - TC 1.6.3
    And Click on 'Generate password' button
    Then 'Password' field is filled with autogenerated password
