Feature: Admin page/ Teacher section functionality
  This feature will cover teacher section of admin page, especially: creating new teachers,
  adding new created teachers to database, checking functionality of different buttons on the given page.

  Background:
    When Enter email heghine96@gmail.com in login page
    And Enter password 1 in login page
    And Click on 'login' button
    When Select teachers section
    And Click on create button on admin page

  @TC1.8.1 @Regression @Smoke
  Scenario: Check functionality of 'create' button in admin dashboard/ teacher section
    Then Check all fields are present in create popup

  @TC1.8.2 @Regression @Smoke
  Scenario: Check functionality of 'X' button in create popup
    And Fill in all required fields
    And Click on 'X' button
    And Click on create button on admin page
    Then Check all input fields are empty in create popup
    And Check admin is not added in the DB

  @TC1.8.3 @Regression @Smoke
  Scenario: Check functionality of 'Generate password' button in create popup
    And Click on 'Generate password' button
    Then 'Password' field is filled with autogenerated password

  @TC1.8.4 @Regression @Smoke
  Scenario: Check functionality to regenerate password
    And Click on 'Generate password' button
    And Get value of generated password
    And Click on 'Generate password' button
    Then See that generated password has been changed
    And Generate button is active

  @TC1.8.5 @Regression @Smoke
  Scenario: Check validations/errors for Teacher name, Teacher surname and Teacher email input fields
    And Type in input fields more than 50 symbols
    And Click on 'Save' button
    Then Check error messages of more symbols filled input fields

  @TC1.8.6 @Regression @Smoke
  Scenario: Check email structure when creating new teacher
    And Fill invalid email
    And Click on 'Save' button
    Then Check invalid email error message

  @TC1.8.7 @Regression @Smoke
  Scenario: Check requirement of all input fields to be filled while creating new teacher
    And Click on 'Save' button
    Then Check error messages of blank input fields

  @TC1.8.8 @Regression @Smoke
  Scenario: Check structure of autogenerated password
    And Click on 'Generate password' button
    Then 'Password' field is filled with autogenerated password
    And Password structure comply with the given requirements

  @TC1.8.9 @Regression @Smoke
  Scenario: Check uniqueness of the Teacher email
    When Fill in existed name, surname
    And Fill existed email
    And Click on 'Generate password' button
    And Click on 'Save' button
    Then Check error message of existed email

  @TC1.8.10 @Regression @Smoke
  Scenario: Check possibility to write in Password field/create popup
    Then Fill in password field no interaction happens because password field is read only

  @TC1.8.12 @Regression @Smoke
  Scenario: Check the possibility of creating new teacher with an existing "Teacher Name" and "Teacher Surname"
    When Fill in existed name, surname
    And Fill non-existed email
    And Click on 'Generate password' button
    And Click on 'Save' button
    Then Teacher is created and displayed in teachers section

  @TC1.8.11 @Regression @Smoke
  Scenario: Check functionality to create New Teacher using valid credentials
    When Fill in all required fields
    And Click on 'Generate password' button
    And Click on 'Save' button
    Then Teacher is created and displayed in teachers section

