Feature: This feature will cover possible scenarios of checking password input in create popup of admin page,
  especially on teachers, students, parent sections.

  Background:
    Given Fill heghine9696@gmail.com and 2kB$8tU#1aO( fields
    And Click on 'login' button

  @TC1.8.3 @TC1.9.11 @TC1.10.12 @Regression @Smoke
  Scenario Outline: Check functionality of 'Generate password' button in create popup
    When Select <section> section
    And Click on 'create' button and open popup
    And Click on 'Generate password' button
    And Save value from password input field
    Then 'Password' field is filled with autogenerated password
    And Check the structure of generated password

    Examples:
      | section  |
      | teachers |
      | students |
      | parents  |


  @TC1.8.4 @TC1.9.12 @TC1.10.13 @Regression @Smoke
  Scenario Outline: Check functionality to regenerate password
    When Select <section> section
    And Click on 'create' button and open popup
    And Click on 'Generate password' button
    And Save value from password input field
    And Click on 'Generate password' button
    Then Check the generated password has been changed
    And Check 'Generate password' button is active

    Examples:
      | section  |
      | teachers |
      | students |
      | parents  |

  @TC1.8.10 @TC1.9.13 @TC1.10.14 @Regression @Smoke
  Scenario Outline: Check possibility to write password in create popup
    When Select <section> section
    And Click on 'create' button and open popup
    Then Check the user is not able to input any data in the password field

    Examples:
      | section  |
      | teachers |
      | students |
      | parents  |


  @TC1.8.8 @TC1.9.14 @TC1.10.15 @Regression @Smoke
  Scenario Outline: Check structure of autogenerated password
    When Select <section> section
    And Click on 'create' button and open popup
    And Click on 'Generate password' button
    Then 'Password' field is filled with autogenerated password
    And Check the structure of generated password

    Examples:
      | section  |
      | teachers |
      | students |
      | parents  |


  @TC1.8.6 @TC1.9.10 @TC1.10.9 @Regression @Smoke
  Scenario Outline: Check structure of email
    When Select <section> section
    And Click on 'create' button and open popup
    And Fill email <invalidEmail>
    And Click on 'Save' button
    Then Check invalid email error message

    Examples:
      | section  | invalidEmail        |
      | teachers | !!invalid@gmail.com |
      | students | invalid{@gmail.com  |
      | parents  | invalidgmail.com    |
      | teachers | invalid@gmailcom    |
      | students | invalid@gmail.c1om  |
      | parents  | invalid@gmail.COM   |
      | teachers | invalid@gmail-.com  |
      | students | invalid@gm--ail.com |
      | parents  | invalid@gm.ail.com  |
      | students | i@gmail.com         |

  @TC1.8.7 @TC1.9.6 @TC1.10.6 @Regression @Smoke
  Scenario Outline: Check the creation of the new user after not filling in all the required fields
    When Select <section> section
    And Click on 'create' button and open popup
    And Click on 'Save' button
    Then Check error messages of blank input fields

    Examples:
      | section  |
      | teachers |
      | students |
      | parents  |


  @TC1.8.5 @TC1.9.16 @TC1.10.20 @Regression @Smoke
  Scenario Outline: Check validations/error messages for input fields when filled more than 50 symbols
    When Select <section> section
    And Click on 'create' button and open popup
    And Fill in input fields more than 50 symbols
    And Click on 'Save' button
    Then Check error messages of more symbols filled input fields

    Examples:
      | section  |
      | teachers |
      | students |
      | parents  |
